
spring:
  application:
    name: demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/data"
    username: "postgres"
    password: "posrgres"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
        "show_sql": "true"
        "format_sql": "true"
        "highlight_sql": "true"
logging:
  level:
    root: "debug"
  charset:
    console: "utf-8"